@startuml start-content--room-index
title start-content--room-index
control 各室インデックス as ri
entity "運転状況（各室）\n取得API" as cond

activate ri
ri -> cond:対象室の\n各機器運転状況問い合わせ
activate cond
cond --> ri:運転状況返却
deactivate cond
ri -> ri:エラー発生している機器に関しては\n・ランプを警告表示\nタブを警告スタイルにする
ri -> ri:取得した運転状況を基に\nSVGマップ画像を作成

@enduml